### ISSUE TITLE
create readOnly anonymous user for argocd

### ISSUE THREAD

**Issue by shsingh** [apcj-f5/hapi.f5labs.dev#42]
- [x] setup DNS record for build.f5labs.dev
- [x] enable web access for https://build.f5labs.dev
- [x] enable anonymous or guest readonly access to argocd ui

**Comment by shsingh** [comment]
build.f5labs.dev is pointing to correct server build.

---

 dig build.f5labs.dev

; <<>> DiG 9.18.15 <<>> build.f5labs.dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47736
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;build.f5labs.dev.              IN      A

;; ANSWER SECTION:
build.f5labs.dev.       30      IN      CNAME   scanme.f5labs.dev.
scanme.f5labs.dev.      30      IN      A       170.64.150.211

;; Query time: 78 msec
;; SERVER: 2001:4860:4860::8888#53(2001:4860:4860::8888) (UDP)
;; WHEN: Sat Jun 03 10:50:46 AEST 2023
;; MSG SIZE  rcvd: 82

**Comment by leonseng** [comment]
https://build.f5labs.dev/ now accessible after https://github.com/apcj-f5/hapi.f5labs.dev/commit/cf63d50e37f966463dc61a82e1a0df6a245c0f77 fixes redirect loop issue.

**Comment by shsingh** [comment]
proposed id/pwd:

id: f5labs.dev
pwd: f5labs.dev

--
aim is to have argo shown to people as part of demo, so it matters little if we 'expose' the id/pwd on github as that is the point.

**Comment by leonseng** [comment]
Added anonymous user with readonly permissions via https://github.com/apcj-f5/hapi.f5labs.dev/commit/4461874b312116a8d3752e2054139e93062b0766. Landing page now shows ArgoCD applications without logging in.

![image](https://github.com/apcj-f5/hapi.f5labs.dev/assets/26860216/f523a8bc-a63f-4e9d-b851-c3aa8f252ddc)
